### ISSUE TITLE
Support mixing dynamic params with static string in same segment

### ISSUE THREAD

**Issue by SilentDepth** [unjs/radix3#11]
### Repro

https://runkit.com/silentdepth/633470604bb52500089af4de

#### One

- `/:msg`
- `/:msg.txt`

The current version sees these 2 patterns as the same, and the second will overrides the first. However, they should be different.

#### Two

- `/:msg.txt`
- `/:msg/uppercase.txt`

Just not sure how these work... The result confuses me.

### Versions

Node: 16.17.0
radix3: 0.1.2

**Comment by pi0** [comment]
Hi @SilentDepth and thanks for repro and explaining. The issue you are facing is that `.txt` is becoming part of the param name as you can see in the output it is `params: Object {msg.txt: "something"}`. 

Currently, radix 3 does not allow combining a param name with some static prefix and/or suffix in the same segment like `/foo/prefix-:param-suffix`.

**Comment by lihbr** [comment]
Hey there, just chiming in with a temporary workaround for this issue/out-of-scope request

I managed to support file extension routing by transforming routes before resolving them, something in that fashion if that makes sense (simplified for clarity purpose):

```typescript
import { createRouter } from "radix3";

const router = createRouter();

router.insert("/foo/:msg/dot/txt");

router.lookup("/foo/something.txt".replace(".", "/dot/"));
```

It's limited, and suboptimal, but it ain't stupid if it works ^^'

I'm curious however if this is out-of-scope for radix 3 or what are the plans, if any, to either support something like that or supporting/replacing colon-based parameters (`:slug`) with square brackets-based parameters (`[slug]`)?

Happy to help~
