### ISSUE TITLE
No export named 'toRouteMatcher'

### ISSUE THREAD

**Issue by AscaL** [unjs/radix3#19]
Hi, I'm using nuxt3 (edge) and, since I updated my dependencies this morning, I'm getting this error:
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/8880943/196116798-cbf522d7-c2ad-43ce-a3bc-70efcc83b6b8.png">

These are the modules used in Nuxt (not sure if relevant)
<img width="214" alt="image" src="https://user-images.githubusercontent.com/8880943/196117524-a352d42c-2a37-4007-8da5-ffd5a14cdcbc.png">

Any idea what this is about?
If you need any more detail please let me know.

Cheers

**Comment by danielroe** [comment]
Yes, this is caused by nuxt3 edge temporarily using an edge release of nitropack. You can use resolutions/overrides to force `"nitropack": "npm:nitropack-edge@latest"` until the next rc.

**Comment by danielroe** [comment]
cc: @pi0
