### ISSUE TITLE
Radix node with multiple parameters

### ISSUE THREAD

**Issue by stuft2** [unjs/radix3#42]
### Describe the feature

Could radix3 support multiple parameters in a single node? The main use case is to represent a composite key in a URL.

For example: `/patient/:name,:dob`.

From RFC 3986
>    Aside from dot-segments in hierarchical paths, a path segment is considered opaque by the generic syntax.  URI producing applications often _use the reserved characters allowed in a segment to delimit scheme-specific or dereference-handler-specific subcomponents_.  For example, the semicolon (";") and equals ("=") reserved characters are often used to delimit parameters and parameter values applicable to that segment.  _The comma (",") reserved character is often used for similar purposes_.  For example, one URI producer might use a segment such as "name;v=1.1" to indicate a reference to version 1.1 of "name", whereas another might use a segment such as "name,1.1" to indicate the same.  Parameter types may be defined by scheme-specific semantics, but in most cases the syntax of a parameter is specific to the implementation of the URI's dereferencing algorithm.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi thanks for issue and rfc reference. Let's track this via https://github.com/unjs/radix3/issues/11
