### ISSUE TITLE
Route-matcher is not matching the most specific rule

### ISSUE THREAD

**Issue by thezzisu** [unjs/radix3#44]
### Environment

```
node: v18.14.1
radix3: "radix3@npm:1.0.0"
```

### Reproduction

See https://github.com/lcpu-club/mirror-frontend. Reproduction steps are:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/21094314/225900002-45685f97-3295-4d4d-a48d-35a0bb8abeb9.png">
<img width="371" alt="image" src="https://user-images.githubusercontent.com/21094314/225900094-9c028bf6-04cb-4d5e-9c71-48e7f1b61684.png">

Simple swapping the rules will affect the output.

_Originally posted by @thezzisu in https://github.com/unjs/nitro/issues/1033#issuecomment-1473735530_
            

### Describe the bug

Route-matcher is not matching the most specific rule.

### Additional context

See https://github.com/unjs/nitro/pull/1033 for more details.

**Comment by pi0** [comment]
I'm not sure issue is with radix3 matcher. Nitro prerenderer is not using radix3 (and that's the issue itself :D) ~> https://github.com/unjs/nitro/issues/1078

**Comment by pi0** [comment]
Appologies. There was an issue only with matchAll. Solving with #45
