### ISSUE TITLE
Match paths ending in a value (such as `/**/*.png`)

### ISSUE THREAD

**Issue by KyleSmith0905** [unjs/radix3#68]
## Context:
I'm trying to add the Cross-Origin-Resource-Policy on dynamically generated OG Images.

I haven't seen anything on Radix3's or Nitro's documentation, I've tested these regardless:
```bash
/__og_image__/og.png # Only gives the header on the homepage's og image.
```
```bash
/*/__og_image__/og.png # Does not provide the header on double nested pages.
```
```bash
/**/__og_image__/og.png # Does not provide the header on any page
```

## Concerns:
I'm wondering if this would be possible as a feature since Radix3 is based on the radix tree? Though, you do support `foo/*/bar`, so idk.

## Feature Request:
Add
```bash
/**/__og_image__/og.png
```
or if the feature already exist, add it to the documentation.

## Willing To Help
I took a look at the code, and it was clean and easy to follow! However I don't have nearly enough knowledge on how this would be done. I'm willing to test the waters, but I don't think I'd be successful. :D

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by dargmuesli** [comment]
@harlan-zw and I are interested in that as well! :heart_eyes:

**Comment by pi0** [comment]
This feature is planned in next major version and already implemented see https://github.com/unjs/radix3/pull/52

**Comment by harlan-zw** [comment]
> This feature is planned in next major version and already implemented see #52

Thanks for the detail, maybe you could help me understand this better. I looked at this code and I can't exactly see how this would work.

The first node needs to be an nth-deeply nested wildcard match.

For example, we need (ideally) a single route rule that will match ALL of the following:
- harlanzw.com/blog/nuxt-3-migration-cheatsheet/__og_image__/og.png
- harlanzw.com/blog/__og_image__/og.png
- harlanzw.com/__og_image__/og.png
- harlanzw.com/some/very/long/url/that/does/not/exist/but/this/is/an/example/__og_image__/og.png

If it is indeed possible with this PR, are you able to provide some code (or point in the right direction) and I can write some unit tests around it for the above?

**Comment by pi0** [comment]
You cannot combine wildcard with following static marcher. For that you need  /** matcher + h3 custom route matcher (with regex)

This is by design for sake of API simplicity/compatiblity in radix3.

Feel free to raise a new issue in h3 or nitro if you need an example of how to do this.

**Comment by harlan-zw** [comment]
Yes, this is what I figured.

Afaik there isn't a way to handle it without using a Nitro / h3 middleware? See https://github.com/harlan-zw/nuxt-og-image/issues/101 for context.

**Comment by pi0** [comment]
- Mixed patten `/*.png` coming with v2 (tracker https://github.com/unjs/radix3/issues/88)
- Wildcard `/**` can be only last segment
