### ISSUE TITLE
Trailing slash matching

### ISSUE THREAD

**Issue by pi0** [unjs/radix3#8]
https://github.com/unjs/radix3/blob/83724b4ee821fb43463598744f05052fdf8eaf97/tests/lookup.test.ts#L95

**Comment by rizrmd** [comment]
This does not work when the route is something like: 

`/editor/:site_id/:page_id`

when I visit `/editor`, my expectation is that it will match with site_id and page_id filled with empty string.

**Comment by pi0** [comment]
@rizrmd Can you please make a new issue with reproduction so i not forget to check? 🙏🏼
