### ISSUE TITLE
Route matcher is always strict about trailing slashes 

### ISSUE THREAD

**Issue by pi0** [unjs/radix3#87]
Context: https://github.com/unjs/nitro/issues/2146

**Reproduction:** https://stackblitz.com/edit/stackblitz-starters-ijst6y

Router created by `createRadixRouter` is non strict about trailing slashes by default. 

While route matcher created by `toRouteMatcher` is strict about trailing slashes. 

(Note: this is a bug but also fix could potentially be breaking behavior change)

**Comment by lwpinion** [comment]
@pi0, does this bug directly relate to the fact that my routes with trailing slashes do not work? Or is this more about making sure radix is consistent about how it handles trailing slashes?
